name: Publish

on:
  push: 
    tags:
      - "v*.*.*"

jobs:
  build:
    runs-on: windows-latest
    defaults:
      run:
        shell: bash

    name: Build

    steps:
      - uses: actions/checkout@v2

      - name: Setup .NET
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: 5.0.x

      - name: Restore Dependencies
        run: dotnet restore

      - name: Set Version
        id: set_version
        run: INPUT=${{ github.ref_name }} echo "::set-output name=version::${INPUT:1}"

      - name: Build
        run: dotnet build -c Release /p:Version=${{ steps.set_version.outputs.version }}

      - name: Zip
        run: 7z a -tzip -mx9 SharpHound-${{ github.ref_name }}.zip bin/Release/net462

      - name: Upload to Release
        uses: softprops/action-gh-release@v1
        with:
          files: SharpHound.zip
